### PR TITLE
[RFR] Memory adapter

### PR DESCRIPTION
**Pull request by Kmaschta**

### CODE REVIEW

**Comment by fzaninotto** [comment]
Great! There are 2 things missing: a Travis config, and a Readme.

**Comment by Kmaschta** [comment]
Travis and README files are already here, I'll update the documentation when there will be several adapters (at least 2).

**Comment by fzaninotto** [comment]
Oh, my bad!

**Comment by fzaninotto** [comment]
Note that the Readme is actually not in sync with the code. You should update the snippet to use the memory adapter

**Pull request merged**
